[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "michigrad"
version = "0.1.0"
description = "Micrograd-style autodiff engine"
authors = [{ name = "Andr√©s Gabriel Kessler" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
